### PR TITLE
Now working with new nrf52 hal, also ran rustfmt

### PR DESCRIPTION
**Pull request by korken89**
Now works with the new nRF52 hal :D

### CODE REVIEW

**Comment by korken89** [comment]
This is dependent on this being merged first: https://github.com/nrf-rs/nrf52-hal/pull/103

**Comment by hannobraun** [comment]
Thank you for the pull request, @korken89!

I don't quite understand the context of this PR. It updates the `nrf52832-hal` dependency from `0.8.0` to `0.8.1`, which shouldn't require any changes. The changes made seem to adapt to my latest changes in nrf52-hal, which aren't released yet and would have to be released as `0.9.0`.

I'm also not a fan of the `rustfmt` changes:
1. I don't quite see the point of consistent formatting. Readable formatting is important, and consistency is not a prerequisite for that. In my experience, consistency can even be a hindrance for readability.
2. I prefer my own style. This might be a matter of taste, but for example, I find those multi-line `use` statements more clear.
3. If we were to start using `rustfmt` (which I could be convinced of; I don't feel *that* strongly about it), it should be introduced in a separate commit that doesn't make any other changes. Mixing it in with other changes makes the review unnecessarily hard.

**Comment by korken89** [comment]
Cool, lets straighten out the import issue in `nrf52-hal` so it can be released, then I will update here  and first make a formatting commit (if acceptable), and based on that add these changes.

> I'm also not a fan of the rustfmt changes.

We have rustfmt specifically to not have theses discussions :) I don't like it 100% either, but all codes feels like ones own code when it all looks the same.
But I am not here to push rustfmt, even though its my RFC for the embedded ecosystem.

**Comment by korken89** [comment]
I have now cleaned out the formating changes

**Comment by hannobraun** [comment]
> We have rustfmt specifically to not have theses discussions :)

To be fair, we're having the discussion because you ran it on all the existing code. I would have accepted pretty much any formatting style in new code :-)

> I have now cleaned out the formating changes

Doesn't seem to be the case. The latest commit (as displayed here on GitHub) still has them.

Also, the following I wrote earlier still holds:

> I don't quite understand the context of this PR. It updates the `nrf52832-hal` dependency from `0.8.0` to `0.8.1`, which shouldn't require any changes. The changes made seem to adapt to my latest changes in nrf52-hal, which aren't released yet and would have to be released as `0.9.0`.

**Comment by hannobraun** [comment]
@korken89 Any update?

**Comment by korken89** [comment]
Hey man, sorry for the long delay.
I'll be getting back here soon, but I think we might need to push the nrf52-hal update first.

**Comment by hannobraun** [comment]
No problem! There's also #93 now, which seems to cover some of the same ground.

**Comment by hannobraun** [comment]
I'm closing this PR, as this repository is being merged into https://github.com/braun-embedded/rust-dw1000. Feel free to re-open the PR there.

**Pull request closed without merging**
